### ISSUE TITLE
All thrusters have the same item ID regardless of material; same for energy cells, etc

### ISSUE THREAD

**Issue by CthonicSyzygies** [BlakeBr0/IronJetpacks#52] opened 2022-01-23 19:46 UTC
**Describe the bug**
Every thruster shares an item id with all other thrusters, of the format "ironjetpacks:thruster" without any specified material. The same is true for energy cells (ironjetpacks:cell) and capacitors (ironjetpacks:capacitor). 

Presumably as a result: when any player logs into our server, they receive a rapid-fire set of recipe advancement notifications which appears to be for every Iron Jetpacks item. On the server, the console spits out information that the recipes could not be loaded (attached)

**To Reproduce**
Have Iron Jetpacks installed, as far as I can tell.

**Expected behavior**
Thrusters of different materials should have separate item ids unique to the material, more akin to ironjetpacks:electrum_thruster and ironjetpacks:diamond_thruster

**Screenshots / Scripts / Logs**
![image](https://user-images.githubusercontent.com/97848658/150694783-1f382e30-8408-4cb4-a6da-0bee408dca6a.png)
![image](https://user-images.githubusercontent.com/97848658/150694795-1a275409-cc63-43ab-9135-e74bc822078a.png)
(this repeats for each material thruster, as well as energy cells with energy cells, etc)
[iron jetpacks unrecognized recipes.txt](https://github.com/BlakeBr0/IronJetpacks/files/7921226/iron.jetpacks.unrecognized.recipes.txt)
Our modlist likely is not relevant but I have included it just to be sure.
[modlist.txt](https://github.com/BlakeBr0/IronJetpacks/files/7921228/modlist.txt)

**Versions (please complete the following information):**
 - Minecraft: 1.18.1
 - Forge: 39.0.19
 - Cucumber: Cucumber-1.18.1-5.0.2
 - Iron Jetpacks: IronJetpacks-1.18.1-5.0.2

**Comment by BlakeBr0** [comment] 2022-01-25 03:01
Can you provide the full log? There might have been an issue that occurred earlier.

**Comment by CthonicSyzygies** [comment] 2022-02-08 00:27
I apologize for the delay, I wasn't sure what log you meant so I kept putting it off. I hav
e just generated a new pack in 1.18.1 with only Iron Jetpacks and JEI (as well as Cucumber), launched it, and verified that with only these parameters, the problem persists. "ironjetpacks:thruster" rather than "ironjetpacks:diamond_thruster" vs "ironjetpacks:iron_thruster". 

here is the log from the world i created and opened with these parameters.
[Jetpacks Log.txt](https://github.com/BlakeBr0/IronJetpacks/files/8019640/Jetpacks.Log.txt)

**Comment by Mitchell5200** [comment] 2022-07-03 14:25
i'm looking at this too in (IronJetpacks-1.18.2-5.1.2) while doing some custom recipe work in atm7 (0.4.18) for our late game stuff, and i've noticed that all of the components are tagged as above, but are correct when you look at their NBT data, it'll give `Id: ironjetpacks:<material>` with the material being whatever it is made of, eg diamond, or gold.

This might also be the cause of a bug i've noticed and thought was reported, where you could make any teir of jetpack with any other jetpack as a base model.
Example 1, a stone jetpack made from a silver one
![2022-07-03_22 20 08](https://user-images.githubusercontent.com/45913837/177044000-34e8bc1c-aefd-4750-8a7c-991ed35a078c.png)
Example 2, a Emerald Jetpack made from a wooden one
![2022-07-03_22 22 54](https://user-images.githubusercontent.com/45913837/177044083-71652728-611a-4692-a486-57ba1542a3d8.png)

**Comment by BlakeBr0** [comment] 2022-07-22 21:21
@Mitchell5200 that is (I believe) a separate issue which will be fixed in the next release.

**Comment by Mitchell5200** [comment] 2022-07-23 15:49
> @Mitchell5200 that is (I believe) a separate issue which will be fixed in the next release.

Excellent to know

**Comment by BlakeBr0** [comment] 2022-11-18 02:56
Is this issue still occurring on the latest version?

**Comment by MasterSloth1** [comment] 2022-12-16 13:17
im using 
* Minecraft - 1.18.2
* Forge - 40.1.86
* Cucumber - 1.18.2-5.0.7.1
* Iron Jetpacks - 1.18.2-5.1.4

and this is still a issue if im reading correct
![image](https://user-images.githubusercontent.com/34207969/208106433-c68bb841-3726-4e3d-9cdb-33b8e0d49b97.png)
![image](https://user-images.githubusercontent.com/34207969/208106468-3b0d3f44-089e-4e98-aa09-6faeab8a2ebc.png)
![image](https://user-images.githubusercontent.com/34207969/208106488-07ca9eb0-1c76-48bd-beb8-700fbaff1764.png)
![image](https://user-images.githubusercontent.com/34207969/208106516-b4c84abe-d1d9-4424-b63b-c44392803501.png)

**Closed as completed** 2023-02-02 04:42 UTC
Labels: Bug
